services:
  sample-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DBNAME=sample-db
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/sample-server
      - /sample-server/node_modules
      - $HOME/.ssh:/home/node/.ssh
      - $HOME/.gitconfig:/home/node/.gitconfig
      - vscode-files-sample-server:/home/node/.vscode-server
    command: sh -c "sleep infinity"

volumes:
  vscode-files-sample-server:
